use sena;
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0001", "5300921882", "Cedula","Andres","Reverte","calle 23 sur # 53 a 13", "5881953", "Masculino", "AndreReve", "5300921882", "AndresReverte@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0002", "6503881456", "Cedula","Albert","Tejedo","Carrera 3 # 18- 45", "5642839", "Masculino", "AlbeTeje", "6503881456", "AlbertTejedo@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0003", "9577616544", "Cedula","Josep","Ballesta","Carrera 7 # 84- 72", "2569596", "Masculino", "JoseBall", "9577616544", "JosepBallesta@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0004", "3726291882", "Cedula","Jose","Cardona","Calle 4 No. 5 – 10", "5409402", "Masculino", "JoseCar", "3726291882", "JoseCardona@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0005", "7507215026", "Cedula","Alejandro","Negrin","Calle 11 No. 4 - 14", "4433385", "Masculino", "AleNegr", "7507215026", "AlejandroNegrin@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0006", "5933705695", "Cedula","Luis","Heredia","Calle 24 N° 5-60", "9904077", "Masculino", "LuHered", "5933705695", "LuisHeredia@gmail.com","02020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0007", "7076308991", "Cedula","Francisca","Casado","Av. Ciudad de Cali No. 6C-09", "2241079", "Femenino", "FranCasa", "7076308991", "FranciscaCasado@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0008", "5762443003", "Cedula","Concepcion","Rodrigues","Calle 48b sur No. 21-13", "2978388", "Femenino", "ConceRo", "5762443003", "ConcepcionRodrigues@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0009", "6843151015", "Cedula","Pilar","Ferrado","Avenida Cra. 60 No. 57-60", "4189890", "Femenino", "PilFer", "6843151015", "PilarFerrado@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0010", "3738882452", "Cedula","Santiago","Vicent","Calle 11 No. 4-21 / 93", "9527236", "Masculino", "SantiVicen", "3738882452", "SantiagoVicent@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0011", "1453035684", "Cedula","Jose","Solera","Calle 10 No. 5-22", "8272941", "Masculino", "JosSole", "1453035684", "JoseSolera@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0012", "6791720847", "Cedula","Juan","Gomariz","Carrera 20 No. 37-54", "5904684", "Masculino", "JuanGo", "6791720847", "JuanGomariz@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0013", "8428676161", "Cedula","Daniel","Mondejar","Av. Calle 19 N° 2-49 Centro", "6167167", "Masculino", "DaniMonde", "8428676161", "DanielMondejar@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0014", "9535243852", "Cedula","Maria","Holgado","Calle 109a N° 17-10 ", "3689113", "Femenino", "MariHol", "9535243852", "MariaHolgado@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0015", "2107778994", "Cedula","Eva","Cañellas","Cr.8a # 15-63", "3939666", "Femenino", "EvaCañe", "2107778994", "EvaCañellas@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0016", "5784300538", "Cedula","Monica","Valenciano","Cr.9 # 74-99", "2299567", "Femenino", "MoniValen", "5784300538", "MonicaValenciano@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0017", "9196660449", "Cedula","Francisco","Maza","Carrera 1 Este No. 17 01", "2164958", "Masculino", "FranMaz", "9196660449", "FranciscoMaza@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0018", "4551364782", "Cedula","Felix","Sevillano","Cr.6 # 17-12", "3259673", "Masculino", "FelSevill", "4551364782", "FelixSevillano@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0019", "5185499769", "Cedula","Miguel","Alcalde","Carrera 7 Calle 26", "6269353", "Masculino", "MigueAlca", "5185499769", "MiguelAlcalde@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0020", "8796974547", "Cedula","Francisco","Armas","Av.19 #152-48", "8449787", "Masculino", "FranArma", "8796974547", "FranciscoArmas@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0021", "4711511895", "Cedula","Marc","Barea","Carrera 13 # 26- 81", "4506133", "Masculino", "MarBare", "4711511895", "MarcBarea@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0022", "9616102103", "Cedula","Francisco","Palacios","Carrera 7 No. 22 - 79", "7147976", "Masculino", "FranPala", "9616102103", "FranciscoPalacios@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0023", "3186806224", "Cedula","Alejandro","Portilla","Cl.90 # 11a-54", "1264829", "Masculino", "AlePort", "3186806224", "AlejandroPortilla@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0024", "4327447388", "Cedula","Victor","Arranz","Calle 12# 2-65", "5679407", "Masculino", "VicArra", "4327447388", "VictorArranz@gmail.com","2020-05-03", "", "Vendedor", "Activo");
insert into usuario (idUsuario, noDocumentoUsuario, tipoDocUsuario, nombreUsuario, apellidoUsuario, direccionUsuario, telefonoUsuario, generoUsuario, nickNameUsuario, claveUsuario, emailUsuario, fechaCreaUsuario, fotoUsuario, tipoUsuario, estadoUsuario)
values ("0025", "9861884926", "Cedula","Francisco","Cano","Calle 45A No. 14-37", "6539485", "Masculino", "FranCano", "9861884926", "FranciscoCano@gmail.com","2020-05-03", "", "Vendedor", "Activo");
select * from usuario;